services:
#  frontend:
#     build: 
#      context: ./frontend
#     container_name: hms-frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/code
#       - /code/node_modules
#     depends_on:
#       - backend
 backend:
   build:
    context: ./backend
   container_name: 'hms-backend'
   restart: always
   ports:
     - "8000:8000"
   volumes:
      - ./backend:/code
   depends_on:
    - db
 db:
   image: mysql:8.4
   restart: always
   container_name: 'hms-db'
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=zxc90zxc
     - MYSQL_DATABASE=hms-db
   volumes:
     - app-db-data:/var/lib/mysql

volumes:
 app-db-data: