services:
 mysql:
   image: mysql:8.4
   container_name: mysql
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=zxc90zxc
     - MYSQL_DATABASE=hms-db
   volumes:
     - ./data:/var/lib/mysql
