services:
 backend:
   build:
    context: ./backend
   restart: always
   ports:
     - "8000:8000"
   volumes:
      - ./backend:/code
   depends_on:
    - db
 db:
   image: mysql:8.4
   restart: always
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=zxc90zxc
     - MYSQL_DATABASE=hms-db
   volumes:
     - app-db-data:/var/lib/mysql

volumes:
 app-db-data: