"""Add Serial No

Revision ID: 13756df8b4e4
Revises: 382d09f9f1db
Create Date: 2024-07-29 16:56:49.935614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13756df8b4e4'
down_revision: Union[str, None] = '382d09f9f1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('serial_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'serial_no')
    # ### end Alembic commands ###
