"""add unique constraint

Revision ID: 619712780f22
Revises: 0fae244d43fa
Create Date: 2024-07-27 06:14:52.399565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619712780f22'
down_revision: Union[str, None] = '0fae244d43fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('u_ix_same_date_slot', 'appointments', ['patient_id', 'date', 'slot_schedule_id'])
    op.create_unique_constraint('u_ix_same_day_slot', 'slotschedules', ['work_place_id', 'slot_id', 'day'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('u_ix_same_day_slot', 'slotschedules', type_='unique')
    op.drop_constraint('u_ix_same_date_slot', 'appointments', type_='unique')
    # ### end Alembic commands ###
